INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, CITY, POSTAL_CODE) VALUES ('1', 'STREET NAME', '1', 'SUBURBONE', 'CHICAGO','1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, CITY, POSTAL_CODE) VALUES ('2', 'STREET NAME', '2', 'SUBURBTWO', 'SYDNEY','1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, CITY, POSTAL_CODE) VALUES ('3', 'STREET NAME', '3', 'SUBURBTHREE', 'UTRECHT','1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, CITY, POSTAL_CODE) VALUES ('4', 'STREET NAME', '4', 'SUBURBFOUR', 'PARIS','1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, CITY, POSTAL_CODE) VALUES ('5', 'STREET NAME', '5', 'SUBURBFIVE', 'DUBLIN','1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, CITY, POSTAL_CODE) VALUES ('6', 'STREET NAME', '6', 'SUBURBSIX', 'VIENNA','1234');
INSERT INTO CONTACT (ID, EMAIL, PHONE) VALUES ('1', 'TEST@TEST.COM', '2387346784');
INSERT INTO CONTACT (ID, EMAIL, PHONE) VALUES ('2', 'TEST@TEST.COM', '2387346784');
INSERT INTO CONTACT (ID, EMAIL, PHONE) VALUES ('3', 'TEST@TEST.COM', '2387346784');
INSERT INTO CONTACT (ID, EMAIL, PHONE) VALUES ('4', 'TEST@TEST.COM', '2387346784');
INSERT INTO CONTACT (ID, EMAIL, PHONE) VALUES ('5', 'TEST@TEST.COM', '2387346784');
INSERT INTO CONTACT (ID, EMAIL, PHONE) VALUES ('6', 'TEST@TEST.COM', '2387346784');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID, CONTACT_ID) VALUES (1, 'NAMEONE', 'LASTNAME', 'ACTIVE', '1','1');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID, CONTACT_ID) VALUES (2, 'NAMETWO', 'LASTNAME', 'ACTIVE', '2','2');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID, CONTACT_ID) VALUES (3, 'NAMETHREE', 'LASTNAME', 'INACTIVE', '3','3');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID, CONTACT_ID) VALUES (4, 'NAMEFOUR', 'LASTNAME', 'INACTIVE', '4','4');

